### ISSUE TITLE
reuseIdentifer Error

### ISSUE THREAD

**Issue by jminutaglio** [DDraiman1990/DroidTimeSelection#8] opened 2021-03-20 22:00 UTC
When running on a physical phone, invoking an instance of DroidTimeSelection() throws a fatal:
```
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'the cell returned from -collectionView:cellForItemAtIndexPath: does not have a reuseIdentifier - cells must be retrieved by calling -dequeueReusableCellWithReuseIdentifier:forIndexPath:'
*** First throw call stack:
(0x18fcbd9d8 0x1a4043b54 0x18fbcc50c 0x190ec6878 0x191ca90bc 0x191cad514 0x191cb1ac0 0x192a32398 0x192f37df4 0x192f3e398 0x192f496e8 0x192e94d7c 0x192ebef40 0x1925584c4 0x18fc3c87c 0x18fc36f50 0x18fc37498 0x18fc36ba0 0x1a699f598 0x1925282f4 0x19252d874 0x105632a64 0x18f915568)
libc++abi.dylib: terminating with uncaught exception of type NSException
*** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'the cell returned from -collectionView:cellForItemAtIndexPath: does not have a reuseIdentifier - cells must be retrieved by calling -dequeueReusableCellWithReuseIdentifier:forIndexPath:'
terminating with uncaught exception of type NSException

```

This **is reproducible** on a physical device (iPhone X, iOS 14.4) - and reproduces on about 50% of invokes.

This **is not reproducible** on the simulator of the same device.

code reference, which is based on the example project:
```

 @IBAction func invokeAction(_ sender: Any) {
        
        let droidSelection = DroidTimeSelection()

        droidSelection.config.timeFormat = .twelve
        
        droidSelection.config.okButtonColor = .green
        droidSelection.config.cancelButtonColor = .red
        droidSelection.clockSelectorConfig.selectionIndicatorColor = .purple
        
        droidSelection.onOkTapped = { [weak self] in
            let value = droidSelection.value //the time selected
            //Your code here.
            print("selected time:", value)
            let hour = value.twentyFourHoursFormat.hours
            let minute = value.twelveHoursFormat.minutes
            print("selected time:", hour, ":", minute)
           
            self?.dismiss(animated: true, completion: nil)
        }

        droidSelection.onCancelTapped = { [weak self] in
            //Your code here.
            self?.dismiss(animated: true, completion: nil)
        }
        
        droidSelection.onSelectionChanged = { [weak self] value in
            //Your code here    
        }
        
        let vc = UIViewController()

        vc.view.addSubview(droidSelection)
        droidSelection
                    .translatesAutoresizingMaskIntoConstraints = false
                droidSelection
                    .leadingAnchor
                    .constraint(
                        equalTo: vc.view.safeAreaLayoutGuide.leadingAnchor,
                        constant: 26)
                    .isActive = true
                droidSelection
                    .trailingAnchor
                    .constraint(
                        equalTo: vc.view.safeAreaLayoutGuide.trailingAnchor,
                        constant: -26)
                    .isActive = true
                droidSelection
                    .centerXAnchor
                    .constraint(
                        equalTo: vc.view.safeAreaLayoutGuide.centerXAnchor)
                    .isActive = true
                droidSelection
                    .centerYAnchor
                    .constraint(
                        equalTo: vc.view.safeAreaLayoutGuide.centerYAnchor)
                    .isActive = true
                droidSelection
                    .topAnchor
                    .constraint(
                        greaterThanOrEqualTo: vc.view.safeAreaLayoutGuide.topAnchor)
                    .isActive = true
                
                vc.modalPresentationStyle = .overFullScreen
                present(vc, animated: true) {
                    UIView.animate(withDuration: 0.3) {
                        //fakeDimView.alpha = 1.0
                    }
                }

    }


```

Any ideas?  TY in advance....

**Comment by DDraiman1990** [comment] 2021-03-29 00:59
While I couldn't reproduce it I still tried to address it with version 2.0.0. Please update and check if this issue went away.

**Comment by jminutaglio** [comment] 2021-03-29 04:11
I will test on a couple physical devices and report back.  TY

**Comment by jminutaglio** [comment] 2021-03-29 14:00
Quick update: 

the test case (invoking on physical device iPhone X, iOS 14.4) that was failing/fatal 50%+ of the time doesn't seem to fail at all now.  :-) 

I will test on some add'l iPhones and some iPads and confirm that things look good...  

More to come - Stay tuned!

**Comment by DDraiman1990** [comment] 2021-03-30 02:22
Thanks for the tests. I'll keep this open a little longer just to make sure. If nothing else is found, I will close this issue.

**Comment by jminutaglio** [comment] 2021-03-30 02:57
Sure thing.  

Ok: tested on a couple of additional iPhone/iPad models.  The test sequences that were failing fairly often in the 1.x version are not failing in the 2.x version, despite all efforts to make it break.  :).  (AKA lots of tests)

This one is fixed!  close it!

**Closed as completed** 2021-03-30 12:23 UTC
Labels: bug
